### PR TITLE
Us issue

### LINKED ISSUE #17: Doesn’t seem to be working for any variation of “US” that I can think of.
Search "US" doesn't work, but United States does

### PR DESCRIPTION
**Pull request by ignaciojimenezr**
Closes #17 
Screenshot 2025-05-29 at 9 29 30 PM
Screenshot 2025-05-29 at 9 30 08 PM

### CODE REVIEW

**Review by oso-jukumari — CHANGES_REQUESTED** [review]
Please submit screenshots of the UI

File: convex/botany.ts [hunk 1]
```diff
@@ -43,18 +44,41 @@ export const searchPlants = query({
     // Start with the first rule
     const firstRule = validRules[0];
     const indexName = `search_${firstRule.index}` as validTypes;
+    // let results = await ctx.db
```
Comment (oso-jukumari) [inline convex/botany.ts:47]: rm comments
